# Future sections (not yet exposed):
# - News
# - Briefings
# - Datasets
# - Dashboards
# - Methods

project:
  type: website
  preview:
    port: 4200

website:
  title: ""
  site-url: https://sh-publichealth.github.io/info-hub
  repo-url: https://github.com/sh-publichealth/info-hub
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true

  navbar:
    logo: assets/images/logo-white.png
    pinned: true
    left:
      - href: index.qmd
        text: Home

      - text: "Our Work"
        menu:
          - href: our-work/tmr/index.qmd
            text: Total Meal Replacement

      - href: data-skills/course-overview.qmd
        text: Data Skills

  sidebar:
    - id: tmr-ops
      title: "TMR Operations Manual"
      style: docked
      search: true
      collapse-level: 1
      contents:
        - text: The Project
          href: our-work/tmr/index.qmd

        - text: Information Sheet
          href: our-work/tmr/info-sheet-01.qmd

        - section: "Operations Manual"
          contents:
            - text: The Study Protocol
              href: our-work/tmr/protocol.qmd
            - text: Evidence Brief
              href: our-work/tmr/evidence-brief.qmd
            - text: Project Approval
              href: our-work/tmr/ethics-approval.qmd
            - text: Eligibility
              href: our-work/tmr/eligibility.qmd

            - section: "Participant Visits"
              contents:
                - text: Participant Flow
                  href: our-work/tmr/visits/participant-flow.qmd
                - text: Overview of Visits
                  href: our-work/tmr/visits/participant-visits.qmd

            - section: "SOPs"
              contents:
                - text: Recruitment SOP
                  href: our-work/tmr/sops/recruitment-sop.qmd
                - text: Screening SOP
                  href: our-work/tmr/sops/screening-sop.qmd
                - text: Height & Weight SOP
                  href: our-work/tmr/sops/height-weight-sop.qmd
                - text: Anthropometry SOP
                  href: our-work/tmr/sops/waist-hip-sop.qmd
                - text: Blood Pressure SOP
                  href: our-work/tmr/sops/bp-heartrate-sop.qmd
                - text: Glucose & Lipids SOP
                  href: our-work/tmr/sops/bloodglucose-lipids-sop.qmd
                - text: Fibroscan SOP
                  href: our-work/tmr/sops/fibroscan-sop.qmd
                - text: Baseline SOP
                  href: our-work/tmr/sops/baseline-sop.qmd

            - section: "Data"
              contents:
                - text: Analysis Plan
                  href: our-work/tmr/data/sap.qmd
                - text: Data Dictionary
                  href: our-work/tmr/data/data-dictionary.qmd
                - text: Data Management Plan
                  href: our-work/tmr/data/data-management-plan.qmd
                - text: Data Anonymisation
                  href: our-work/tmr/data/anonymisation.qmd
                - text: Data Sharing
                  href: our-work/tmr/data/data-sharing.qmd

    - id: data-skills
      title: "Data Skills Training"
      style: docked
      search: true
      collapse-level: 1
      contents:
        - text: Course Overview
          href: data-skills/course-overview.qmd
        - text: Our Modules
          href: data-skills/module-overview.qmd
#        - text: Module Skeleton
#          href: data-skills/module-skeleton.qmd

freeze: auto

format:
  html:
    format-links: true
    toc: true
    toc-depth: 2
    description: false
    theme:
      - flatly
    css:
      - assets/css/styles.css
      - assets/css/briefing-ash.css
      - assets/css/grid.css

resources:
  - assets/graphics/Coat_of_Arms_of_Saint_Helena.png

bibliography: references.bib
csl: https://www.zotero.org/styles/harvard-cite-them-right
# touch: 2026-03-06 15:19:34.007
