project:
  type: book
  output-dir: ../_site/data-skills
  render:
    - "*.qmd"

book:
  title: "St Helena Public Health Data Skills Programme"
  subtitle: "Training and Practice Guide"
  author: "Ian Hambleton"
  date: last-modified

  chapters:
    - index.qmd
    - course-overview.qmd
    - modules.qmd

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    theme: cosmo

execute:
  freeze: auto
