** Live visit-map preflight v2. Reads real raw data; exports event metadata only.
** args: DATA_ROOT VISIT_MAP. Defaults are the explicit SHG locations.
version 19
clear all
args data_root visit_map
set more off
if `"`data_root'"' == "" local data_root "C:/yoshimi-hot/output/analyse-sth/sh007-total-meal-replacement/stata"
if `"`visit_map'"' == "" local visit_map "C:/yoshimi-hot/output/analyse-sth/sh003-diabetes-registry/info-hub/scripts/stata/tmr/monitoring/config/tmr-visit-map.csv"
confirm file "`data_root'/data_raw/tmr_full_redcap_api_extract_latest.dta"
use "`data_root'/data_raw/tmr_full_redcap_api_extract_latest.dta", clear
confirm variable redcap_event_name
capture confirm variable redcap_repeat_instance
if _rc gen long redcap_repeat_instance = .
capture confirm numeric variable redcap_repeat_instance
if _rc destring redcap_repeat_instance, replace
gen long repeat_instance = redcap_repeat_instance
replace repeat_instance = 0 if missing(repeat_instance)
gen byte measurement_row = 0
local measurement_vars ///
    visit_date_cm weight waist hip sbp1 dbp1 sbp2 dbp2 sbp3 dbp3 glucose ///
    diabetes_meds hypertension_meds smoking smoking_past core_measurements_complete ///
    visit_date_anth anthropometry_complete ///
    visit_date_hba1c hba1c hba1c_complete ///
    visit_date_lm results_date hba1c_copy alt ast alp bilirubin_total albumin ///
    protein_total ggt hb cholesterol_total cholesterol_hdl cholesterol_ldl ///
    triglyceride sodium potassium urea creatinine egfr lab_measurements_complete ///
    visit_date_em fibroscan_date lsm_kpa lsm_iqr cap_dbm cap_sd ///
    eq_mob eq_sc eq_ua eq_pd eq_ad eq_vas ///
    paid01 paid02 paid03 paid04 paid05 paid06 paid07 paid08 paid09 paid10 ///
    paid11 paid12 paid13 paid14 paid15 paid16 paid17 paid18 paid19 paid20 ///
    ipaq_walk_days ipaq_walk_mins ipaq_mod_days ipaq_mod_mins ///
    ipaq_vig_days ipaq_vig_mins ipaq_sit_mins expanded_measurements_complete ///
    visit_date_he he_currency he_currency_oth he_insulin_supplied ///
    he_metformin_supplied he_antihyp_supplied he_notes health_economics_complete
foreach v of local measurement_vars {
    capture confirm variable `v'
    if !_rc replace measurement_row = 1 if !missing(`v')
}
keep if measurement_row == 1
keep redcap_event_name repeat_instance
duplicates drop
sort redcap_event_name repeat_instance
if _N == 0 {
    di as error "No measurement events were found in the real raw extract."
    exit 2000
}

capture confirm file `"`visit_map'"'
local map_exists = !_rc
if `map_exists' {
    tempfile confirmed_map
    preserve
        import delimited using `"`visit_map'"', clear varnames(1) stringcols(_all)
        foreach v in redcap_event_name repeat_instance planned_visit display_order visit_label {
            confirm variable `v'
        }
        replace redcap_event_name = strtrim(redcap_event_name)
        foreach v in repeat_instance planned_visit display_order {
            destring `v', replace
        }
        replace repeat_instance = 0 if missing(repeat_instance)
        isid redcap_event_name repeat_instance
        keep redcap_event_name repeat_instance planned_visit display_order visit_label
        save `confirmed_map'
    restore
    merge 1:1 redcap_event_name repeat_instance using `confirmed_map', keep(master match) nogen
}
else {
    gen byte planned_visit = .
    gen double display_order = .
    gen str100 visit_label = ""
}
** The baseline event name is confirmed in the supplied data dictionary.
replace planned_visit = 1 if redcap_event_name == "baseline_arm_2" & repeat_instance == 0 & missing(planned_visit)
replace display_order = 1 if redcap_event_name == "baseline_arm_2" & repeat_instance == 0 & missing(display_order)
replace visit_label = "Baseline" if redcap_event_name == "baseline_arm_2" & repeat_instance == 0 & strtrim(visit_label) == ""
quietly count if missing(planned_visit,display_order) | strtrim(visit_label) == ""
local n_unmapped = r(N)
if `n_unmapped' > 0 | `map_exists' == 0 {
    capture mkdir "`data_root'/config"
    local draft_date = subinstr(strtrim("`c(current_date)'")," ","_",.)
    local draft_time = subinstr("`c(current_time)'",":","",.)
    local draft_csv "`data_root'/config/tmr-visit-map-draft_`draft_date'_`draft_time'.csv"
    order redcap_event_name repeat_instance planned_visit display_order visit_label
    export delimited using `"`draft_csv'"'
    di as error "Visit map needs confirmation. Unmapped real event/instance combinations: `n_unmapped'"
    di as result "Event-only draft written to: `draft_csv'"
    di as result "No participant IDs or measurements are included in this CSV."
    di as error "Complete or return the draft for event mapping, then save the confirmed map as:"
    di as error `"`visit_map'"'
    di as error "No monitoring PDF has been generated by this run."
    exit 459
}
di as result "Real measurement events are covered by the supplied visit map."
